/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#DDE7F5",
        "surface-container-highest": "#E0EDFB",
        "secondary-container": "#DBEAFE",
        "tertiary-container": "#506066",
        "primary-container": "#1D4ED8",
        "on-surface-variant": "#475569",
        "surface-bright": "#FFFFFF",
        "on-secondary-fixed-variant": "#1E40AF",
        "status-scam-bg": "#FEECEE",
        "status-safe-green": "#0F9D58",
        "outline": "#64748B",
        "on-secondary-container": "#1E40AF",
        "inverse-surface": "#0B192C",
        "surface-variant": "#EFF6FF",
        "secondary-fixed": "#DBEAFE",
        "border-subtle": "#E2E8F0",
        "surface-tint": "#2563EB",
        "surface-container-high": "#EBF3FC",
        "on-tertiary": "#FFFFFF",
        "surface-ice-blue": "#DDEEF5",
        "primary-fixed-dim": "#93C5FD",
        "on-secondary": "#FFFFFF",
        "surface": "#F8FAFC",
        "surface-container": "#F0F6FD",
        "tertiary": "#39484E",
        "inverse-primary": "#93C5FD",
        "primary-fixed": "#DBEAFE",
        "on-error": "#FFFFFF",
        "error-container": "#FFDAD6",
        "status-safe-bg": "#E6F4EA",
        "on-tertiary-fixed-variant": "#3A494F",
        "outline-variant": "#CBD5E1",
        "on-primary-fixed-variant": "#1D4ED8",
        "on-primary-container": "#DBEAFE",
        "on-secondary-fixed": "#172554",
        "on-background": "#0F172A",
        "on-tertiary-container": "#C9DAE1",
        "on-primary": "#FFFFFF",
        "on-primary-fixed": "#172554",
        "tertiary-fixed-dim": "#B8C9D0",
        "brand-violet-hover": "#1D4ED8",
        "on-error-container": "#93000A",
        "on-surface": "#0F172A",
        "surface-container-lowest": "#FFFFFF",
        "on-tertiary-fixed": "#0E1E23",
        "brand-violet-vibrant": "#2563EB",
        "primary": "#2563EB",
        "border-purple-subtle": "#DBEAFE",
        "error": "#BA1A1A",
        "surface-container-low": "#F8FAFC",
        "tertiary-fixed": "#D4E5EC",
        "brand-indigo-hero": "#0B192C",
        "background": "#F8FAFC",
        "secondary": "#3B82F6",
        "secondary-fixed-dim": "#93C5FD",
        "inverse-on-surface": "#F8FAFC",
        "status-scam-red": "#E52534",
        "brand-blue-hero": "#0B192C",
        "brand-blue-vibrant": "#2563EB",
        "brand-blue-hover": "#1D4ED8",
        "border-blue-subtle": "#DBEAFE"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        full: "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin": "2rem"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: []
};
